# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b828ce712a9b761b9766991aaaa9ed0a65433fdfd69ce2cdbdc8e0aceab387696b07e18dddbb2ba5d49be5d8fcc55783366f4ed66b64017d863716b9d3a53cd4

test:
  secret_key_base: cb8aee6ed38ab9883599e3c8ed1476e6269b2290350c17c39c0291d14338e146f33dce60d7a9eaea9d1c4fcbbbb5d1f8ba75c346f98b86e2c65339b67142861e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
